# -------------------------------------------------------------------------
# File: assemble.py
# Description: Assemble final markdown document from annotated slides
# Context: PresentationNotes pipeline - final assembly stage
# Author: Greg Tate
# -------------------------------------------------------------------------

"""
Assemble Stage

Builds the final markdown document from annotated slide notes.
Each slide section includes an embedded image of the slide followed
by the detailed notes generated from the transcript.

This stage is deterministic (no LLM).
"""

import re
import shutil
from datetime import datetime
from pathlib import Path
from typing import List

from presentation_notes.models import SlideNotes


def assemble_presentation_notes(
    slide_notes: List[SlideNotes],
    output_path: Path,
    title: str = "Presentation Notes",
    slides_dir: Path | None = None
) -> Path:
    """
    Build the final markdown document with embedded slide images.

    Creates a markdown file where each slide has:
    - An embedded image of the slide
    - The timestamp range
    - Detailed notes from the transcript

    Slide images are copied into an 'images' subfolder next to the
    output file so the markdown references work correctly.

    Args:
        slide_notes: List of SlideNotes objects (sorted by slide number)
        output_path: Path for the output markdown file
        title: Presentation title for the document header
        slides_dir: Source directory containing slide images

    Returns:
        Path to the generated markdown file
    """

    # Ensure output directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Set up images directory next to the output file
    images_dir = output_path.parent / f"{output_path.stem}_images"
    images_dir.mkdir(parents=True, exist_ok=True)

    # Copy slide images to the output images directory
    _copy_slide_images(slide_notes, images_dir, slides_dir)

    # Build the document
    sections: List[str] = []

    # Document header
    sections.append(_build_header(title, len(slide_notes)))

    # Table of contents
    sections.append(_build_table_of_contents(slide_notes))

    # Individual slide sections
    for notes in slide_notes:

        # Determine relative image path from the output file
        image_filename = Path(notes.image_path).name
        relative_image_path = f"{images_dir.name}/{image_filename}"

        section = _build_slide_section(notes, relative_image_path)
        sections.append(section)

    # Footer
    sections.append(_build_footer())

    # Write the document
    content = "\n".join(sections)
    output_path.write_text(content, encoding="utf-8")

    print(f"  Document created: {output_path}")
    print(f"  Slide images:     {images_dir}")

    return output_path


def _build_header(title: str, slide_count: int) -> str:
    """
    Build the document header section.

    Args:
        title: Presentation title
        slide_count: Number of slides

    Returns:
        Formatted header markdown
    """

    date_str = datetime.now().strftime("%Y-%m-%d")

    return (
        f"# {title}\n\n"
        f"**Generated**: {date_str}  \n"
        f"**Slides**: {slide_count}  \n\n"
        f"---\n"
    )


def _build_table_of_contents(slide_notes: List[SlideNotes]) -> str:
    """
    Build a table of contents linking to each slide section.

    Args:
        slide_notes: List of SlideNotes objects

    Returns:
        Formatted TOC markdown
    """

    lines = ["\n## Table of Contents\n"]

    for notes in slide_notes:

        # Create anchor-compatible slug from the title
        anchor = _title_to_anchor(notes.slide_title, notes.slide_number)
        lines.append(
            f"- [Slide {notes.slide_number}: {notes.slide_title}](#{anchor})"
        )

    lines.append("\n---\n")
    return "\n".join(lines)


def _build_slide_section(notes: SlideNotes, image_path: str) -> str:
    """
    Build the markdown section for a single slide.

    Includes the slide image, timestamp, and notes content.

    Args:
        notes: SlideNotes object for this slide
        image_path: Relative path to the slide image

    Returns:
        Formatted slide section markdown
    """

    section_parts = [
        f"\n## Slide {notes.slide_number}: {notes.slide_title}\n",
        f"**Timestamp**: {notes.timestamp_range}\n",
        f"![Slide {notes.slide_number}]({image_path})\n",
    ]

    # Add the notes content
    if notes.notes_markdown:
        section_parts.append(notes.notes_markdown)

    section_parts.append("\n---\n")

    return "\n".join(section_parts)


def _build_footer() -> str:
    """Build the document footer."""

    return (
        "\n---\n\n"
        "*Generated by VideoToNotes - Presentation Notes Pipeline*\n"
    )


def _copy_slide_images(
    slide_notes: List[SlideNotes],
    images_dir: Path,
    slides_dir: Path | None
) -> None:
    """
    Copy slide images to the output images directory.

    Args:
        slide_notes: List of SlideNotes with image paths
        images_dir: Destination directory for images
        slides_dir: Source directory containing original slide images
    """

    for notes in slide_notes:
        src = Path(notes.image_path)

        if not src.exists() and slides_dir:
            # Try looking in the slides directory
            src = slides_dir / src.name

        if src.exists():
            dst = images_dir / src.name
            shutil.copy2(str(src), str(dst))

            # Update the image path to the new location
            notes.image_path = str(dst)
        else:
            print(f"  Warning: Slide image not found: {src}")


def _title_to_anchor(title: str, slide_number: int) -> str:
    """
    Convert a title to a markdown anchor slug.

    Args:
        title: Section title
        slide_number: Slide number (used in prefix)

    Returns:
        Anchor-compatible slug string
    """

    # Build the full heading text as markdown would see it
    full_text = f"Slide {slide_number}: {title}"

    # Convert to lowercase
    slug = full_text.lower()

    # Remove non-alphanumeric characters except hyphens and spaces
    slug = re.sub(r"[^\w\s-]", "", slug)

    # Replace spaces with hyphens
    slug = re.sub(r"\s+", "-", slug)

    # Remove leading/trailing hyphens
    slug = slug.strip("-")

    return slug
